### ISSUE TITLE
找不到登陆的入口

### ISSUE THREAD

**Issue by shenjing023** [izghua/go-blog#1]
```go
al := c.Group("/login")
		{
			authLoginV := validate.NewValidate().NewAuthLoginV.MyValidate()
			al.GET("/",m.Permission("console.login.index"),consoleAuth.Login)
			al.POST("/",m.Permission("console.login.store"),authLoginV,consoleAuth.AuthLogin)
		}
```
get请求返回验证码图片，登陆的页面呢

**Comment by xzghua** [comment]
> ```go
> al := c.Group("/login")
> 		{
> 			authLoginV := validate.NewValidate().NewAuthLoginV.MyValidate()
> 			al.GET("/",m.Permission("console.login.index"),consoleAuth.Login)
> 			al.POST("/",m.Permission("console.login.store"),authLoginV,consoleAuth.AuthLogin)
> 		}
> ```
> 
> get请求返回验证码图片，登陆的页面呢

go提供的只是接口,后台登录是用vue写的,你访问 http://localhost:8081/backend   会自动跳转登录页面!

这是在两个地方都有设置,一个是路由里,如果走 backend 会自动找vue生成的静态文件,   还有一个是我设置了一个中间件  https://github.com/izghua/go-blog/blob/master/middleware/routerNoFound.go#L17   如果没找到的链接里有个 backend  会自动跳转后端登录页面!  
另外,我已经把vue生成好的页面放在  static/console 下了,  如果你有需要改后台页面,  可https://github.com/izghua/go-blog-backend  这个下载下来,改后 重新build  复制进去即可
