### ISSUE TITLE
大佬你好，我成功安装了您的博客，但后台没看到管理员注册的按钮，请问如何登录后台。

### ISSUE THREAD

**Issue by wagmie** [izghua/go-blog#8]
还是说我没正确部署导致无法注册。

**Comment by wagmie** [comment]
谢谢大佬，已经找到了是:localhost:8081/backend/register,问下大佬前后端是如何通讯的啊？

**Comment by xzghua** [comment]
@wagmie 后台页面是用vue写的, 生成静态文件放到go的项目里一起了
前台是 直接go模板解析嵌套的

https://github.com/izghua/go-blog-backend 这是后台的前端页面代码

**Comment by wagmie** [comment]
好的非常感谢大佬，虽然还是没太看懂
