### ISSUE TITLE
文档中没有后台默认账号密码

### ISSUE THREAD

**Issue by ilostycom** [izghua/go-blog#9]
如题所述， 也没有说明可以生成后台账号密码的命令之类的 点击到博客的安装教程也没有说明

**Comment by xzghua** [comment]
@tszl004 后台没有默认账号, 有个注册接口, 正常默认只允许注册两个账号, 两个账号注册后,这个接口不再允许注册 

能否注册几个, 可以修改配置文件进行设置..  


/backend/register  这是注册路由

**Comment by xzghua** [comment]
https://github.com/izghua/go-blog/blob/master/router/auth/auth.go#L108  这是限制的代码
